cask_args appdir: '/Applications'

brew 'ccache'
brew 'coreutils'
brew 'ffmpeg'
brew 'git'
brew 'glew'
brew 'glfw3'
brew 'gradle'
brew 'imagemagick'
brew 'mono'
brew 'openssl'
brew 'python'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 's3cmd'
brew 'subversion'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
brew 'webp'
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'

brew cask 'android-ndk'
brew cask 'android-sdk'
